#######################################################################################
# Book settings
title : Realfaglig programmering
author: Universitetet i Oslo
logo: 'Logo-UiO.png'

# Information about where the book exists on the web
description: >-
  Ressurssider for realfaglig programmering (NAT3000 og ProFag).

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : false

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://andreasdh.github.io/NAT3000/
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
