name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Upgrade pip, setuptools, and wheel
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install attrs

      - name: Build book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          git init
          git config user.name "Github Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git checkout master

          jupyter-book build .
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./_build/html
          cname: realprog.no
